### ISSUE TITLE
Swiffy支持swf导入，优势介绍不妥

### ISSUE THREAD

**Issue by shifujun** [Tencent/Fanvas#1]
不清楚Swiffy是否是后改成以swf文件作为输入的。
https://developers.google.com/swiffy/convert/upload?hl=zh-CN

**Comment by kenkozheng** [comment]
谢谢指正。文中swiffy主要指google开发的，安装在flash IDE上的插件。
对于大部分国内开发者来说，也许只能使用到这个插件版本了。（这边尝试访问swiffy的在线版，访问失败。）

swiffy如果是开源的，fanvas就没有存在的必要了，swiffy真的非常优秀。不过暂时没看到相关开源的内容，而且这个工具11年发布后，并没看到后续的更新。

**Comment by sy-ww-sun** [comment]
这个工具的创意非常好。期待指导解决的问题是：后台处理如何按需调用？一是要为这个工具配置什么运行环境，二是转换速度是否可以尽量加快。

**Comment by sy-ww-sun** [comment]
还有一个很重要的技术：SWF中音频的提取与同步，本项目是否有同样简洁好用的办法？。。。

**Comment by kenkozheng** [comment]
需要flash环境，建议在windows上转化。swf内的元素，无法实现按需提取，建议在fla中先做好合适的swf。暂时音频没有导出，但欢迎扩展fanvas，增加音频的导出功能。
