### ISSUE TITLE
报错：Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0.

### ISSUE THREAD

**Issue by RockyRen** [Tencent/Fanvas#7]
我用fanvas转换某个swf后，得到如下错误：
_Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The image argument is a canvas element with a width or height of 0._
![fanvas](https://user-images.githubusercontent.com/7037806/44826453-ad96e800-ac41-11e8-8552-b0b30c5ab1fd.png)
错误定位到fanvas3-all.js的1263行代码的drawImage。使用如下方式可以规避问题：
```javascript
cacheCanvas.width = cacheCanvas.width || 1;
cacheCanvas.height = cacheCanvas.height || 1;
ctx.drawImage(cacheCanvas, offX, offY, cacheCanvas.width/scale, cacheCanvas.height/scale);
```
能请问导致这个问题的原因是什么吗？

**Comment by kenkozheng** [comment]
请先排除项目自身的影响。
具体邮件和QQ联系解决。

**Comment by kenkozheng** [comment]
针对chrome68版本，做了兼容处理

**Comment by LarryZhao0616** [comment]
请问 /scale 是什么意思？ @RockyRen  非常感谢

**Comment by MritLeesin** [comment]
你好，我在  chrome 76的版本上还是存在相同的问题
