### ISSUE TITLE
能否在配置里多加个参数，循环播放，或者停留在最后一帧？

### ISSUE THREAD

**Issue by JinwenXie** [Tencent/Fanvas#9]
最近做一个项目，刚接触到这个工具，觉得完美，后边发现不能停留在最后一帧，一直循环播放，有点尬

**Comment by kenkozheng** [comment]
欢迎使用。这个项目没有维护有一段时间了，你可以利用已有的接口实现你需要的功能，有一个逐帧回调接口，基于这个接口，你可以判断当前帧数，如果符合要求则停止动画。
